name: Build and Package Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Make build script executable
      run: chmod +x build-extension.sh
    
    - name: Build Extension
      run: ./build-extension.sh
    
    - name: Upload Extension Package
      uses: actions/upload-artifact@v3
      with:
        name: ai-tutor-extension
        path: ai-tutor-extension.zip
    
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: ai-tutor-extension.zip
        tag_name: v${{ github.run_number }}
        name: AI Tutor Extension v${{ github.run_number }}
        body: |
          ## AI Tutor Chrome Extension
          
          ### Features
          - AI-powered tutoring for math, reading, writing, grammar, and vocabulary
          - Developer test mode for math problems with actual solutions
          - LaTeX/LaTeX fraction reconstruction for proper math rendering
          - Text selection and highlighting with context-aware responses
          - Multi-select mode for reading comprehension
          - Image analysis capabilities
          - Site-specific detection and responses
          - Security features and abuse detection
          
          ### Installation
          1. Download the `ai-tutor-extension.zip` file
          2. Extract the zip file
          3. Open Chrome and go to `chrome://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          
          ### Setup
          After installation, you'll need to set your Claude API key:
          1. Open the extension
          2. Type: `update api key YOUR_CLAUDE_API_KEY_HERE`
          3. Press Enter
          
          Get your API key from: https://console.anthropic.com/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
